# Generated by Django 6.0 on 2025-12-25 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('maintenance_interval_hours', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_operating_hours', models.PositiveIntegerField()),
                ('last_service_hours', models.PositiveIntegerField()),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='machine.machinetype')),
            ],
        ),
    ]
